### PR TITLE
Download dmg automatically for darwin

### LINKED ISSUE #29: Give .dmg preference in case of mac user agent
I was wondering if there would be interest in having a way to provide downloading a `dmg` instead of the `zip` file for OSX users. The issue with the `zip` file is that the it usually stays in the `~/Downloads` folder which makes it impossible for auto updates to work (https://github.com/Squirrel/Squirrel.Mac/pull/186, https://github.com/Squirrel/Squirrel.Mac/issues/182). 

Nuts does something similar by way of [file preference](https://github.com/GitbookIO/nuts/blob/52c91a66c9269e3dac754c276c10333a966f545f/lib/utils/platforms.js#L92)

Thoughts?

### LINKED ISSUE #41: The `/download` route should return the DMG and not ZIP on macOS
The `/download` route is useful for providing a direct link to the latest release, but currently, it returns the ZIP file, which is only meant for updates, and not the DMG file, which is meant for end-users.

### PR DESCRIPTION
**Pull request by rwwagner90**
This downloads dmgs automatically for darwin, and downloads the zip when it is an update. Everything else should remain mostly unchanged.

Closes #53 
Closes #41 
Closes #29

### CODE REVIEW

**Comment by rwwagner90** [comment]
@leo any chance I could get a review on this?

**Comment by rwwagner90** [comment]
@AndyBitz @leo who should I ping about getting this merged?

**Comment by Aarbel** [comment]
@rwwagner90 if you'd like to retweet https://twitter.com/ClementFtNd/status/1224684320213938178, @leo seems alive but maybe busy

**Comment by leo** [comment]
This looks great, thank you!

It took us a while to understand what is actually going on, but it seems like there's a [bug](https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-544997415) with Apple's official unarching tool.

Releasing this now.

**Comment by rwwagner90** [comment]
Thanks so much for merging and releasing @leo!

**Pull request merged**
